OPENAI_API_KEY = "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"
DEEPSEEK_API_KEY = "sk-fec883e5a2554af4ac38cdcfc5dc1291"
DEFAULT_MODEL = "gpt-4.1-mini-2025-04-14"
FALLBACK_MODEL = "deepseek-reasoner"